### PR TITLE
Add notes about email & url regexes

### PR DESCRIPTION
**Pull request by saippuakauppias**

### CODE REVIEW

**Comment by saippuakauppias** [comment]
@crazyguitar , Hi! Could you add "hacktoberfest" in topics to this repository? :)

```
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest.

Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.
```

https://hacktoberfest.digitalocean.com/

**Comment by crazyguitar** [comment]
I think you can fix issues instead of providing other projects' link. Also, after Hacktoberfest end, could I remove topic? I can help you finish your  missions but I don't want to become an advertiser permanently.

**Comment by saippuakauppias** [comment]
> I think you can fix issues instead of providing other projects' link

If I just copy the regular expressions from there, should I link to the original?

> Also, after Hacktoberfest end, could I remove topic?

Yes, of course!

**Comment by crazyguitar** [comment]
> If I just copy the regular expressions from there, should I link to the original?

Hmm, this is a great question. I think if you copy/paste snippet, you need to provide references. However,  I think most projects use similar reg patterns. Could you try to "google" other well-known projects, like facebook/folly, and refer to those projects if you want to just copy/paste.

**Comment by saippuakauppias** [comment]
I have not found any other versions, it is probably better to postpone this idea.

PS: You can just accept this PR and close it, this is also allowed in hacktoberfest. Thank you :)

**Comment by crazyguitar** [comment]
ok

**Pull request closed without merging**
